name: Download MxBuild
description: Downloads the given mx build
inputs:
  mxbuild-version:
    description: 'The mx build version. Example: 7.23.8.58888'
    required: true
  mx-version:
    description: 'The Mendix version. Example: 7.23.8'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download MxBuilds ${{ inputs.mx-version }}
      shell: powershell
      working-directory: mxbuilds
      run: |
        $ProgressPreference = "SilentlyContinue" 
        $url = "https://cdn.mendix.com/runtime/mono-mxbuild-${{ inputs.mxbuild-version }}.tar.gz"
        Invoke-WebRequest -Uri $url -OutFile "./mxbuild-${{ inputs.mxbuild-version }}.tar.gz"
        mkdir "./mxbuild-${{ inputs.mx-version }}"
        C:\Windows\System32\tar.exe -xzf "./mxbuild-${{ inputs.mxbuild-version }}.tar.gz" -C "./mxbuild-${{ inputs.mx-version }}"
        Remove-Item "./mxbuild-${{ inputs.mxbuild-version }}.tar.gz"